version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: code/Dockerfile
    ports:
      - "8000:8000"
    container_name: platoon-pynalia-api
    hostname: platoon-pynalia-api
    networks:
      - frontend

  front:
    build:
      context: ..
      dockerfile: pynalia-front/Dockerfile
    ports:
      - "4200:4200"
    container_name: platoon-pynalia-front
    hostname: platoon-pynalia-front
    networks:
      - frontend

networks:
  frontend:
    driver: bridge